# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile CXX with /usr/bin/c++
CXX_FLAGS = -O3 -DNDEBUG -I/Users/masahiko/Programs/head_pose_estimation/demo/. -I/Users/masahiko/Programs/head_pose_estimation/demo/.. -I/usr/include/ni -I/usr/local/include   

CXX_DEFINES = 

